RedHatInsights/insights-frontend-builder-common

src/release.sh
Changes the env name of the target deploy repo to DEPLOY_REPO
For some time fall back to REPO if DEPLOY_REPO is unset
=> favor DEPLOY_REPO but use REPO as a fallback

src/release.sh
This works by cloning a bare, shallow, copy of the build repo directly
into the .git directory, and then setting config.bare=false.  This is
essentially what git does anyway when you do a normal git clone, however
git clone typically doesn't let you clone into an existing directory. git
clone tries to checkout HEAD, but this technique skips that part, allowing
the files already in the dist directory to remain. See also
https://stackoverflow.com/a/28180781/2355944 .
Fixes #10
=> Prevent destroying history of the target branch

src/release.sh
If the target repo did not have the branches pre-configured, then the
release script would fail.  This commit adds the ability to create new
branches.
---
@iphands Please review.
I tested this code by extracting it to a separate shell script locally, creating a empty repo on my personal GitHub account, and then creating all kinds of combinations of branches.  This was how I found the empty repository case.
With this PR, you can change your process for creating build repos to just create a completely empty repo without branches, and then giving that to the team in question.
=> Allow for creation of branches when they don't exist in the target repo

src/after_success.sh, src/bootstrap.sh, src/nightly.sh
I think this may be an approach we want to take. Essentially, we can set up travis to do a cron job on a certain branch (`nightly` in this case) and then it should rebuild and deploy it to a `nightly` environment.
=> Add a nightly build script

src/nightly.sh
Slammed some stuff into master, but travis only actually clones one branch, so I need to make sure I add the remote correctly and then update it so that we can pull down all the branches. This will allow the nightly build to always pick up the latest changes on master.
=> update nightly to actually get the most recent version of master

src/akamai_cache_buster/bustCache.py
This script will clear the cache for everything under the paths for a specific app (so long as it has paths listed in the source of truth). 
to run: python3 bustCache.py /path/to/edgerc nameOfApp
A few more notes:
- your edgerc needs read/write permision for the eccu API on akamai (not open CCU)
- only works on production akamai
- requests take about 30 minutes to finish, right now I am the only one emailed when it finished, we should send this to a mailing list of frontend devs in the future
- will not work on apps that don't have paths listed in source of truth, also not super friendly about errors at the moment
=> switch to eccu based cache busting (actually works)

src/Jenkinsfile
Switches from only running the cache buster on storybook deployments to running for all deployments. Not to be merged until we confirm it's working okay on storybook
=> enable cache purge for all apps

src/release.sh
jira: https://issues.redhat.com/browse/RHCLOUD-7916
This script adds a new key to the info file with an array of PF dependencies. The output looks likes this:
```
"patternfly_dependencies": ["@patternfly/react-core@4.47.0","@patternfly/react-icons@4.7.4","@patternfly/react-styles@4.7.3","@patternfly/react-table@4.16.7"]
```
It only looks for direct production dependencies.
=> Add pf-dependnecies to app.info.json file.

src/after_success.sh
As for new github repository, it creates `main` branch as default branch.
It will be helpful to have both default branches in existing script.
=> consider 'main' branch into condition while releasing

src/akamai_cache_buster/bustCache.py
possible fix for: https://issues.redhat.com/browse/RHCLOUD-15557
- update yml endpoints to use console.redhat.com
- add apps/appName revalidate rule
- allow empty paths attribute as it is no longer required
Currently the script sends request to bust only these resources:
```XML
<match:recursive-dirs value="cost-management">
<revalidate>now</revalidate>
</match:recursive-dirs>
```
If the `apps/` prefix is not automatically added (which i doubt), this would mean, that it only revalidates the `HTML` templates and never any other static assets. This would be probably the reason why we had to introduce JS hashes in the first place.
Also, from the script, I would assume the payload should also have rules for `/beta` assets, but it does not have them. The have the same rule 4x in the payload. My …
=> Update cache busting

src/nginx_conf_gen.sh
Since we want to fully utilize nginx config in Docker, we have to escape `NGINX_CONFIGURATION_PATH` in orfer to preserve it for docker generation.
When running this script the app info can already be generated, so let's check if these files exists in dist folder. If so let's not re-create them.
=> Adjust generation of nginx and app info

src/frontend-build.sh
* `$GIT_BRANCH` does not populate the same way when a manual build is triggered
* `$JOB_NAME` should be a consistent option that will always contain "build-master"
=> Fix issue when building manual container images

src/quay_push.sh
Since hac-core dockerfile and nginx is at root, but the source code folder is located in `frontend` let's use `APP_ROOT` when building image.
=> USE either APP_ROOT or pwd in quay push

src/frontend-build.sh
Currently, the automation only tracks on build-master, but we also need to support build-main.
=> Fix IS_PR label for main branch builds

src/frontend-build.sh, src/quay_push.sh
For [RHCLOUD-18589](https://issues.redhat.com/browse/RHCLOUD-18589):
* Use IMAGE from the calling PR to determine an image.
* Don't enforce `-frontend`
=> Add support any image name without -frontend

src/frontend-build.sh
This will not affect any of the currently running Travis builds or Jenkins jobs for Akamai.
* Updates the frontend-build script to use the Caddy based fe build container. 
* Will not affect any repo with an existing `nginx.conf` or `Dockerfile`
* All other repos will now run on Caddy instead of Nginx as new commits hit the build / deploy pipeline.
=> Migrate to Caddy for frontend container builds

src/frontend-build.sh
This patch changes the ref of the frontend-build-container that we pull to c892522 which contains a change to Caddyfile generation code to properly interpolate the ROUTE_PREFIX variable provided by the operator
=> Update frontend-build-container to c892522

src/Jenkinsfile
We believe the deletion of files after a successful `rsync` is causing Akamai issues. We are turning it off while we investigate further at the suggestion of our Akamai experts.
=> [RHCLOUD-23162] Temporary fix for chunk-loading

src/frontend-build.sh
We only need to grab chrome config if we are in fact building chrome
=> Make get_chrome_config conditional

src/frontend-build.sh
Jenkins job has started failing out of nowhere because sometimes we try to remove the container that no longer exists. Until we figure out why, we should unblock our PR checks.
=> Remove container only if it exists.

src/cacheBuster.Dockerfile
This patch adds a new Dockerfile for an akamai cache purge based on akamai's upstream stuff modified to work in a Red Hat environment
=> New cache buster dockerfile

src/frontend-build.sh
RHCLOUD-25502
The chrome service is currnelty sourcing this config elsewhere, rather than add the time and complexity to our build runs, let's just skip this function. Keeping the code around in case they later move to our build flow.
=> Prevent get_chrome_config from being called

src/releaser.Dockerfile
We will need to use releaser in the better docs, so let's add caddy and other dependencies to run the better docs.
=> Install caddy to the releaser image

build_deploy.sh, pr_check.sh
We need to surface releaser image in cloudservices quay organizatio. Releaser image will be later on used to release better platfrom docs to app-interface.
=> Add release scripts for releaser image

src/frontend-build.sh
This patch switches to using DOCKER_CONFIG env var for the docker config to provide better compatibility with various versions of docker and podman.
=> Switch to using DOCKER_CONFIG for better compatibility

src/frontend-build.sh
This patch should create both preview and stable builds in the same container. The result is that the preview build will land in the normal spot, but the preview will land under /opt/app-root/src/dist/preview.
After this patch is submitted we'll need to update the caddy config in the build container to look in the new directory for the preview build.
This patch has a shim in it to maintain compatibility with the current system:
```
build $WORKSPACE/build $BETA
```
Once the build container has been updated we'll change that to:
```
build $WORKSPACE/build true
```
And that should take care of it.
This requires carful review as I can't run this and test it.
=> Create both preview and stable builds for each build

src/frontend-build.sh
If a job is aborted the build container can be left around. We detect it on start and delete it.
=> Detect container and if it is running delete it

src/frontend-build.sh
Users have the option to set a duration for the life of an image pushed to Quay. If no parameter is set, it defaults to 3 days.
=> Optional parameter for quay image life duration

src/frontend-build.sh
Looks like we had an error in how we referred to APP_ROOT in some of the build functions
=> Fix APP_ROOT in build funcitons

src/frontend-build.sh
Reverts RedHatInsights/insights-frontend-builder-common#181
Reverting this because https://gitlab.cee.redhat.com/insights-platform/frontend-build-container/-/merge_requests/57 was reverted. The change caused problems with the builds.
=> Revert "Use latest 75bdb61 image build"

src/frontend-build.sh, src/local-build.sh, src/release.sh
replaces NodeJS requirement with `jq` from "top level" operations (NodeJS is required within the actual build containers). 
It is also required in [migrate.sh](https://github.com/RedHatInsights/insights-frontend-builder-common/blob/9892b661a14aadf9facf2903b87c883737089774/src/migrate.sh) but unsure if that is actually used
Should avoid `NodeJS` requirements issues on build nodes
=> feat: remove NodeJS dependency at root level

src/frontend-build.sh
Pass the `GLITCHTIP_TOKEN` env'-var from the parent environment to the frontend build-container's.
To be used for Sentry-CLI integration inside frontend-apps' build flow.
Example use case:  
The OCM UI (insights app name: 'openshift'), [utilizes][2] sentry CLI to generate and publish sourcemaps.   The CLI's `release` command requires an authentication token, which can be obtained inside jenkins CI runs, by [attaching][1] the `*uhc_insights_platform` secret to the job-template definition.
After OCM UI's migration to build-containers (in staging), this token has become unavailable, apparently as result of the isolated env' inside the FE build-container.
This PR aims to accommodate that use-case, until a more permanent/thought-out solution is implemented.
For future …
=> fix(frontend-build): expose glitchtip token in build-container

build_deploy.sh, pr_check.sh, src/releaser.Dockerfile
- Fixes the failing image build process by bumping the base image tag
- Refactors the `pr-check.sh` and `build-deploy.sh` scripts to leverage the CICD-tools ilbrary
=> Fix for the releaser image not building

src/frontend-build.sh
We run verification in a separate github action and don't need to run it again during the container image build. Other teams might want that as well so making this into another env var that can be set.
=> Make running verification optional

src/frontend-build.sh
These variables can be used by the sentry webpack plugin to upload source maps.
=> src/frontend-build: pass along sentry variables

Dockerfile
Managing this is too onerous. I'm setting it to latest. Whatever theoretical value there is in determinism it is far outweighed by the burden of managing this.
=> Change caddy-ubi to latest

server_config_gen.sh
Format the Caddyfile so that it passes caddy fmt validation. Without these changes, a warning is issued when the container runs.
```
2025/04/23 16:40:36.210	WARN	Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies
```
=> Correct formatting and paths in generated Caddyfile

Dockerfile
The universal_build.sh script makes use of the NPM_BUILD_SCRIPT envvar to customize the build step, but the envvar cannot currently be used.
Adding `ARG NPM_BUILD_SCRIPT=""` to the Dockerfile allows NPM_BUILD_SCRIPT to be modified via a build-arg
=> add NPM_BUILD_SCRIPT as a build arg

Dockerfile
The uploading of source maps needs to be done through konflux now. In order to do this, sentry vars passed into the tekton build-args in order to enable the sentry webpackplugin. This should have no affect on anything else as its just setting up variables
=> feat(RHINENG-19424): Create Sentry vars

Dockerfile.hermetic
Running test in the container build slows down image builds tremendously.
Unless this is required to be done during build, it can be removed.
=> feat: remove test and lint during build

Dockerfile
The build is accessing the wrong path, and the issue is the way we're mounting the secret.
=> fix(Sentry): Update the secretId for sentry var

Dockerfile, README.md, parse-secrets.sh
Let's add option to pass additional secrets to build so they can later be used in the build commands. This PR adds parse secrets script which mounts additional secrets, parses the .env file and sets the variables.
=> Add option to pass additional secrets to build
