RedHatInsights/insights-frontend-builder-common

src/release.sh
I think this line cloned and did nothing with the clone
@Kinlaw you agree
=> remove dead code

src/after_success.sh
k.i.s.s. for issue #3 
@Fryguy
=> let users optionally define how they want release.sh to be invoked

src/Jenkinsfile
switched to an edgerc file that should let the script hit the ECCU API endpoint
=> switched edgerc

src/Jenkinsfile, src/akamai_cache_buster/bustCache.py
Fixes error where jenkins will fail is the app has no path in the Source of Truth
=> Fix app name error

src/akamai_cache_buster/bustCache.py
Adds FMS mailing list to the cache buster so FMS will be notified when a new frontend is deployed and the cache is busted
=> added mailing list

src/nightly.sh
nightly should not have lint or tests because it changes so often
=> remove lint and test from nightly env

src/release.sh
Add check for yarn.lock files and then fallback to empty array
=> Add check for yarn and fallback (just in case)

src/nginx_conf_gen.sh
* Functions need to be at the top of the file
=> Fix nginx config generation

src/release.sh
jira: https://issues.redhat.com/browse/RHCLOUD-16826
cc @john-dupuy
=> Add FEC dependencies info

src/Jenkinsfile, src/jenkins_agent.Dockerfile
We need to migrate Jenkins instance to the new OSDv4 cluster it will require changes in the Jenkinsfile.
=> [WIP] Jenkins instance is migrated to OSDv4 cluster and it requires changes

src/Jenkinsfile, src/jenkins_slave.Dockerfile
Reverts RedHatInsights/insights-frontend-builder-common#63
=> Revert "[WIP] Jenkins instance is migrated to OSDv4 cluster and it requires changes"

src/Jenkinsfile, src/jenkins_agent.Dockerfile
Original PR: #64
Migrates Jenkins to the new cluster 
cc @quarckster
=> Jenkins instance is migrated to OSDv4 cluster and it requires changes

src/frontend-build.sh, src/frontend.Dockerfile, src/nginx_conf_gen.sh, src/universal_build.sh
* Base Dockerfile for building frontends in containers.
=> [RHCLOUD-17026] Add Dockerfile for FE container pipeline

src/frontend-build.sh
* Remove trailing whitespace on `frontend-build.sh`
=> Fix whitespace issue on frontend-build

src/frontend-build.sh
* Will setup PR images to expire in 3 days
* Will not label master or main images; they are permanent.
=> Use dynamic Docker label for PR images

src/frontend-build.sh
* fixes a missing `;` on nginx conf
=> Bump build container ref

src/akamai_cache_buster/bustCache.py
Should purge cache from /apps/<app-name>/index.html which is required for chrome deployments
=> Add template purge script to bustCache script

src/frontend-build.sh
Adds a /metrics endpoint to Caddy images
=> Expose metrics endpoint in Caddyfile

src/frontend-build.sh
Reverts RedHatInsights/insights-frontend-builder-common#111
=> Revert "Update frontend-build.sh"

src/frontend-build.sh
This patch adds env vars for the chrome config
=> Add env vars for chrome config

src/local-build.sh
This PR adds a new local dev script and bumps the container version
=> Build container bump and new local dev script

src/Jenkinsfile
=> Remove logic to alter known_hosts

src/frontend-build-history.sh, src/frontend-build.sh, src/local-build.sh
This is like my 4th attempt at a solution to this problem.
=> Add image history retention during builds

src/frontend-build.sh
Reverts RedHatInsights/insights-frontend-builder-common#127
=> Revert "Remove container only if it exists."

src/frontend-build.sh
We need to support conditionally changing the webpack config based on the branch.
=> Add support for beta builds

src/frontend-build.sh
* Adds gcc as a package to the build container to unblock hac-dev
=> Publish new gcc enabled build container

src/stable-merge.yml
Added the file for automatically merging to a stable branch. This is just for reference, it is not in the correct directory to activate on this repo.
=> added github action file as reference

src/frontend-build.sh
This patch switches to a new version of the build container that handles doing both builds at once. This makes it so we don't have to stand up the build container twice, and docker cp twice, which can put some load on the jenkins nodes and potentially cause failures under the wrong circumstances.
=> Use new build container that handles universal builds itself.

src/frontend-build.sh
This bumps the build container version to pull in new app.info.json generation code
=> [RHCLOUD-28602] - Bump the build container version

src/frontend-build.sh
We've hit multiple problems in the wild with the build script refactors. This PR will be for working through those.
=> Fixes after refactor

src/frontend-build-history.sh, src/frontend-build.sh, src/local-build.sh
This will revert the build script to before the big refactor
=> Reverted to before build script refactor

src/frontend-build.sh
=> Update build image tag

src/frontend-build.sh
=> Bump version of build container

src/frontend-build.sh
This uses the latest tag for the frontend-builder-common and then also adds multiarch support for frontends
=> Update build script with latest for builder image and multiarch support

src/frontend-build.sh
We want to make sure we are doing docker login before we interact with docker
=> Move login to top of the script

src/frontend-build.sh
Adding support for tagging + building security-compliance branch.
=> add support for tagging the security-compliance branch

Dockerfile
The paths for the scripts in the Dockerfile were wrong
=> Change paths for scripts in Dockerfile

application.Dockerfile
We need to pull in a newer version to close some CVEs
=> Bump caddy UBI

Dockerfile
Reverts RedHatInsights/insights-frontend-builder-common#228
=> Revert "Change paths for scripts in Dockerfile"

application.Dockerfile
This updates the caddy ubi tag to latest
=> Update application.Dockerfile for caddy ubi

Dockerfile.hermetic, README-hermetic-build.md
Make small  changes for non-hosted hermetic builds.
=> feat(rhcloud-40657): Updates for hermetic build Dockerfile ecosystem cert checks
